### PR TITLE
Adds ability to run container test and to containerize and upload docker images

### PR DESCRIPTION
**Pull request by armenaktoggle**
examples here:
- https://github.com/toggleglobal/daily-check/tree/main/.github/workflows

### CODE REVIEW

**Review by rfoyard — COMMENTED** [review]
You are using `${{github.run_number}}` to tag the image, what do you think of using the git short sha instead ?
You can add an extra step like this one
```yaml
    - name: Setup environment variables
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
```
And use the `SHORT_SHA` variable instead of the run number
```yaml
${{github.repository}}:${{github.ref_name}}-${{env.SHORT_SHA}}
# or just the sha
${{github.repository}}:${{env.SHORT_SHA}}
```

**Comment by armenaktoggle** [comment]
> You are using `${{github.run_number}}` to tag the image, what do you think of using the git short sha instead ? You can add an extra step like this one
> 
> ```yaml
>     - name: Setup environment variables
>       run: |
>         echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
> ```
> 
> And use the `SHORT_SHA` variable instead of the run number
> 
> ```yaml
> ${{github.repository}}:${{github.ref_name}}-${{env.SHORT_SHA}}
> # or just the sha
> ${{github.repository}}:${{env.SHORT_SHA}}
> ```

the problem is not getting a unique build tag, but rather a sequential number.
this way I know that toggleglobal/dailycheck:main-8 comes after toggleglobal/dailycheck:main-7 ... 
it's easier imo

**Comment by rfoyard** [comment]
> the problem is not getting a unique build tag, but rather a sequential number. this way I know that toggleglobal/dailycheck:main-8 comes after toggleglobal/dailycheck:main-7 ... it's easier imo

Ok, just suggesting 😀. I tend to move away from versions in favour of tags because it ties the docker image to the exact source but it's indeed a bit less practical to navigate in the docker hub list.
Your method makes sense too, I'll approve ✅

**Review by rfoyard — DISMISSED** [review]

**Comment by armenaktoggle** [comment]
sorry @rfoyard 
changed back to your initial suggestion as it allows a more seamless flow

**Review by rfoyard — APPROVED** [review]

**Pull request merged**
